import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} bg-gray-300`}>
        <Navbar brandName="E-Commerce v1.50" />
        <div className="xl:w-2/3 mx-auto shadow-[0px_0px_15px_0px_rgba(0,0,0,0.3)] bg-white">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
